more complete checkpoint resume behavior

diff --git a/skypilot/examples/run_notebook.yaml b/skypilot/examples/run_notebook.yaml
--- a/skypilot/examples/run_notebook.yaml
+++ b/skypilot/examples/run_notebook.yaml
@@ -12,6 +12,7 @@ file_mounts:
   ~/.config/gh: ~/.config/gh  # for github cli
 
 setup: |
+  set -e  # Exit if any command failed.
   conda activate ray
   sudo mount 192.168.179.186:/filestore /mnt/filestore
   echo 'export SCPRINTER_DATA=/mnt/filestore/scprinter' >> ~/.bashrc
@@ -29,6 +30,7 @@ setup: |
   fi
 
 run: |
+  set -e  # Exit if any command failed.
   conda activate ray
   nohup jupyter-lab --LabApp.token='' --no-browser --port 3456 > ~/jupyter.log 2>&1 &
   jupyter nbconvert --to html --execute /mnt/filestore/240315-scPrinter/ray_pipeline/02.train_bulk_model.ipynb
diff --git a/skypilot/sky-bolero.yaml b/skypilot/sky-bolero.yaml
--- a/skypilot/sky-bolero.yaml
+++ b/skypilot/sky-bolero.yaml
@@ -27,6 +27,7 @@ file_mounts:
     mode: MOUNT
 
 setup: |
+  set -e  # Exit if any command failed.
   conda activate ray
   sudo mount 192.168.179.186:/filestore /mnt/filestore
   echo 'export SCPRINTER_DATA=/mnt/filestore/scprinter' >> ~/.bashrc
@@ -44,5 +45,6 @@ setup: |
   fi
 
 run: |
+  set -e  # Exit if any command failed.
   conda activate ray
   nohup jupyter-lab --LabApp.token='' --no-browser --port 9990 > ~/jupyter.log 2>&1 &
